### ISSUE TITLE
scaleM Problem with family = "mopt" and "opt"

### ISSUE THREAD

**Issue by robustport** [msalibian/RobStatTM#13]
scaleM does not work with the choices "mopt" and "opt":

> library(RobStatTM)
> set.seed(123)
> r <- rnorm(150, sd=1.5)
> scaleM(r)
[1] 1.416166
> scaleM(r, family = "mopt")
Error in .psi.conv.cc(psi, cc) : 
  Coef. for Modified Optimal psi function not of length 6
> scaleM(r, family = "opt")
Error in .psi.conv.cc(psi, cc) : 
  Coef. for Optimal psi function not of length 16

**Comment by msalibian** [comment]
`mscale` (which is the same function as `scaleM`) was originally written as an internal function. The arguments `delta`, `tuning.chi` and `family` need to be specified explicitly (and be coherent). If one changes the default values of any of them, currently the others need to be changed accordingly. For example, this works
```
> scaleM(r, family = "mopt", tuning.chi = lmrobdet.control(family='mopt', bb=0.5)$tuning.chi)
[1] 1.487873
```
BUT, this also works (AND it's wrong):
```
> scaleM(r, delta = 0.25, family = "mopt", tuning.chi = lmrobdet.control(family='mopt')$tuning.chi)
[1] 2.756092
```
The right way to compute a 25% BDP scale estimator would be
```
> scaleM(r, delta = 0.25, family = "mopt", tuning.chi = lmrobdet.control(family='mopt', bb = 0.25)$tuning.chi)
[1] 1.500108
```

I will change the code of `scaleM` so that the argument `tuning.chi` is overwritten internally to `lmrobdet.control(family=family, bb=delta)$tuning.chi`. Removing `tuning.chi` from the argument list is a cleaner/better solution, but will require very careful attention because this function is used extensively in the package, and each call will need to be changed.

**Comment by robustport** [comment]
Matias, thanks for your comments, which are quite clear, and helpful.
I am now thinking your fix should be just for scaleM as a separate function for which the function mscale is not an alias, and leave mscale as is for internal use and do not expose it via help(mscale).  What do you think?

**Comment by msalibian** [comment]
Done, as described above (scaleM does not have the tuning.chi argument anymore).
