### ISSUE TITLE
lmrobdetDCML missing component

### ISSUE THREAD

**Issue by harrysouthworth** [msalibian/RobStatTM#7]
lmrobdetMM.RFPE doesn't work. The lmrobdetDCML object needs the control object attached.

m <- lmrobdetDCML(mpg ~ wt + hp, data = mtcars)
> lmrobdetMM.RFPE(m)
Error in .psi.conv.cc(psi, cc) : tuning constant 'cc' is not numeric
> m$control <- lmrobdet.control()
> lmrobdetMM.RFPE(m)
[1] 0.1644712

The same issue also breaks lmrobdetLinTest, and the same fix applies.

**Comment by msalibian** [comment]
Thanks for catching these oversights @harrysouthworth. Neither of those inference methods can be used with DCML estimators (only with M or MM regression estimators). Although the help pages indicated this restriction, it was not enforced in the code. I've just pushed fixes for both of these functions, so that they now check the class of their arguments and fail if they are not appropriate.

**Comment by msalibian** [comment]
@harrysouthworth A work around, for an approximate version of what you may need, would be to use the robust stepwise procedure with an MM estimate (computed with `lmrobdetMM` to get a smaller model, and then use `lmrobdetDCML` to compute the DCML estimate for that subset of explanatory variables).

**Comment by msalibian** [comment]
Closed.
